spring.config.import=optional:file:env.properties
spring.application.name=cheap-radar-backend

application.client.google.provider=GOOGLE
application.client.google.maximumTickets=3
application.client.google.maximumRequests=2
application.client.google.apiKey=${GOOGLE_API_KEY}
application.client.google.endpoint=${GOOGLE_ENDPOINT}

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/postgres?prepareThreshold=0
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-prepared-statements=false
spring.datasource.hikari.max-open-prepared-statements=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

application.mail.sender=${MAIL_SENDER}
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


server.port=${PORT:8080}

app.jwt.secret=${SUPABASE_JWT_SECRET:super-secret-dummy-key-for-local-testing-only-keep-it-long}
app.jwt.expiration-ms=86400000

